---

- name: Cloud provider bastion deployment
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - create
    - bastion
    - bastion_create

  tasks:

    - name: Deploy bastion cloud configuration resources
    # TODO: Clean up vars section (see inv.d/host_vars/localhost)
      vars:
        service_name: bastion
        tf_vars:
          service_name: "{{ service_name }}"
          cred_file: "{{ gcp_data['cred_file'] | expanduser }}"
          project_name: "{{ gcp_data['project'] }}"
          region_name: "{{ project_region }}"
          network_name: "{{ project_data['network']['name'] }}"
        tf_instance_vars: "{{ project_data['services'][service_name] }}"
      terraform:
        project_path: "{{ inventory_dir |
          default(ansible_inventory_sources[0])
          }}/../terraform/{{ cloud_provider }}/{{ service_name }}"
        state: present
        force_init: yes
        lock: yes
        variables: "{{ tf_vars | combine(tf_instance_vars) }}"
        backend_config: "{{ tf_backend_config }}"
      when:
        - cloud_provider is defined
        - cloud_provider == 'gcp'

  post_tasks:

    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory
