---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Download GitLab runner repository installation script
  get_url:
    url: "{{ runner_repository_installation_script_url }}"
    dest: /tmp/runner_install_repository.sh
    validate_certs: "{{ runner_download_validate_certs }}"

- name: Install GitLab runner repository
  command: bash /tmp/runner_install_repository.sh

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Gitlab python block
  block:

    - name: Install python3-pip
      vars:
        packages:
          - python3-pip
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: Upgrade PIP
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install GitLab python libraries
      pip:
        name: python-gitlab
        state: present
        executable: pip3

  when: install_python_gitlab
