---

cloud_provider: gcp

gcp_data:
  cred_file: ~/gcp/gitlab-creds.json
  project: inspired-access-273514
  cred_kind: serviceaccount
  ssh_user: ansible
  ssh_pubkey: ~/gcp/id_rsa.pub

service_data:
  network: project
  region: europe-west2
  gitlab:
    instances:
      - name: 1
        disk:
          size_gb: 50
          source_image: projects/centos-cloud/global/images/family/centos-8
          # source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
        machine_type: n1-standard-1
        zone: europe-west2-a
        create_external_ip: yes
    scopes:
      - https://www.googleapis.com/auth/compute
    fw_data:
      - name: allow-internal
        description: Allow all UDP/TCP ports internally
        allowed:
          - ip_protocol: tcp
            ports:
              - '0-65535'
          - ip_protocol: udp
            ports:
              - '0-65535'
          - ip_protocol: icmp
        source_ranges:
          - '10.128.0.0/9'
        pri: 65534
      - name: allow-icmp
        description: Allow ICMP externally
        allowed:
          - ip_protocol: icmp
        pri: 65534
      - name: allow-ssh
        description: Allow SSH externally
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
        pri: 65534
      - name: allow-gitlab
        description: GitLab service port
        allowed:
          - ip_protocol: tcp
            ports:
              - '4483'
        pri: 65534
      - name: allow-gateway
        description: Network Proxy
        allowed:
          - ip_protocol: tcp
            ports:
              - '3128'
        pri: 65534
  vault:
    instances:
      - name: 1
        disk:
          size_gb: 50
          source_image: projects/centos-cloud/global/images/family/centos-8
          # source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
        machine_type: n1-standard-1
        zone: europe-west2-a
        create_external_ip: no
      - name: 2
        disk:
          size_gb: 50
          source_image: projects/centos-cloud/global/images/family/centos-8
          # source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
        machine_type: n1-standard-1
        zone: europe-west2-b
        create_external_ip: no
      - name: 3
        disk:
          size_gb: 50
          source_image: projects/centos-cloud/global/images/family/centos-8
          # source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
        machine_type: n1-standard-1
        zone: europe-west2-c
        create_external_ip: no
    scopes:
      - https://www.googleapis.com/auth/compute
    fw_data:
      - name: allow-internal
        description: Allow all UDP/TCP ports internally
        allowed:
          - ip_protocol: tcp
            ports:
              - '0-65535'
          - ip_protocol: udp
            ports:
              - '0-65535'
          - ip_protocol: icmp
        source_ranges:
          - '10.128.0.0/9'
        pri: 65534
      - name: allow-icmp
        description: Allow ICMP externally
        allowed:
          - ip_protocol: icmp
        pri: 65534
      - name: allow-ssh
        description: Allow SSH externally
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
        pri: 65534
      - name: allow-internal-vault
        description: Internal Vault traffic - replication, request forwarding & raft gossip traffic
        allowed:
          - ip_protocol: tcp
            ports:
              - '8200-8201'
        source_ranges:
          - '10.128.0.0/9'
        pri: 64000
      - name: allow-vault-api
        description: External Vault API
        allowed:
          - ip_protocol: tcp
            ports:
              - '8200'
        pri: 65000
