---

- name: Include tasks for cloud provider
  vars:
    files:
      - "{{ cloud_provider }}.yml"
      - "unsupported.yml"
  include_tasks:
    file: "{{ cloud_item }}"
  loop: "{{ query('first_found', files) }}"
  loop_control:
    loop_var: cloud_item
