arena: gitlab
cred_file: "{{ gcp_data['cred_file'] }}"
project: "{{ gcp_data['project'] }}"
cred_kind: "{{ gcp_data['cred_kind'] }}"
region: "{{ gcp_data['region'] }}"
zone: "{{ gcp_data['zone'] }}"
scopes:
  - https://www.googleapis.com/auth/compute
# source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
source_image: projects/centos-cloud/global/images/family/centos-8
ssh_user: ansible
ssh_pubkey: ~/gcp/id_rsa.pub
fw_data:
  - name: allow-internal
    allowed:
      - ip_protocol: tcp
        ports:
          - '0-65535'
      - ip_protocol: udp
        ports:
          - '0-65535'
      - ip_protocol: icmp
    source_ranges:
      - '10.128.0.0/9'
    pri: 65534
  - name: allow-icmp
    allowed:
      - ip_protocol: icmp
    pri: 65534
  - name: allow-ssh
    allowed:
      - ip_protocol: tcp
        ports:
          - '22'
    pri: 65534
  - name: allow-gitlab
    allowed:
      - ip_protocol: tcp
        ports:
          - '4483'
    pri: 65534

