---

vault_src: "https://releases.hashicorp.com/vault/1.5.0/vault_1.5.0_linux_amd64.zip"
vault_chksum: "sha256:322393aee141c4711fc5f9e1df9f461af3a861e59b8d4d0a85e82477cdbc73a0"
vault_bin_path: "/usr/bin"
vault_conf: "/etc/vault/config.hcl"
vault_tls_disable: "false"
vault_certs: "/etc/vault/certs"
vault_cn: "{{ ansible_fqdn }}"
vault_cc: "UK"
vault_on: "Vault"
vault_privkey: "{{ vault_certs }}/{{ ansible_fqdn | regex_replace('^www\\.', '') }}.pem"
vault_csr: "{{ vault_certs }}/{{ ansible_fqdn }}.csr"
vault_certfile: "{{ vault_certs }}/{{ ansible_fqdn | regex_replace('^www\\.', '') }}.crt"
vault_protocol: "{{ vault_tls_disable | bool | ternary('http', 'https') }}"
vault_addr: "{{ ansible_fqdn }}"
vault_port: 8200
vault_cluster_port: 8201
vault_user: "vault"
vault_uid: "8201"
vault_group: "vault"
vault_gid: "8201"
vault_service: "vault"
vault_profile: "/etc/profile.d/vault.sh"
vault_data_path: "/data/vault"
vault_ui: "true"
