---

- name: GitLab Runner registration
  hosts: runner
  become: yes
  gather_facts: no
  tags:
    - runner
    - runner_register

  tasks:

    - name: Run gitlab runner registration role
      vars:
        gitlab_server_address: "{{ hostvars[groups['gitlab'][0]]['inventory_hostname'] }}"
        gitlab_server_port: 4483
        gitlab_runner_registration_token: "{{ runner_registration_token }}"
      include_role:
        name: ansible-role-runner-register
