---

- name: Setup localhost configuration
  hosts: localhost
  gather_facts: no

- import_playbook: localhost_sshkeys.yml
- import_playbook: localhost_install.yml
- import_playbook: localhost_cloudinit.yml
