---

- name: Prepare SSH keys
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Create ssh key pair directory
      ansible.builtin.file:
        path: "{{ vm_ssh_key_path | dirname }}"
        state: directory

    - name: Create ansible ssh key pair
      community.crypto.openssh_keypair:
        path: "{{ vm_ssh_key_path }}"
        type: "{{ vm_ssh_key_type }}"
        comment: "{{ vm_ssh_comment }}"
