---

- name: Enable HashiCorp Vault approle
  hosts: vault
  become: yes
  gather_facts: yes
  tags:
    - vault
    - vault_approle

  tasks:

    - name: Run vault server approle role
      include_role:
        name: ansible-role-vault-approle
