---

- name: Remove HashiCorp Vault
  hosts: vault
  become: yes
  gather_facts: yes
  tags:
    - never
    - remove
    - vault_remove

  tasks:

    - name: Run vault server removal role
      include_role:
        name: ansible-role-vault-remove
