---

- name: Configure HashiCorp Vault
  hosts: vault
  become: yes
  gather_facts: yes
  tags:
    - vault
    - vault_configure

  tasks:

    - name: Run vault server configuration role
      include_role:
        name: ansible-role-vault-configure
