---

- name: Unseal HashiCorp Vault
  hosts: vault
  gather_facts: yes
  become: yes
  tags:
    - vault
    - vault_unseal

  tasks:

    - name: Run vault server unseal role
      include_role:
        name: ansible-role-vault-unseal
