---

- name: Enable HashiCorp Vault sshkeysign
  hosts: vault
  become: yes
  gather_facts: yes
  tags:
    - vault
    - vault_sshkeysign

  tasks:

    - name: Run vault server sshkeysign role
      include_role:
        name: ansible-role-vault-sshkeysign
