---

vault_tls_disable: "false"
vault_protocol: "{{ vault_tls_disable | bool | ternary('http', 'https') }}"
vault_addr: "{{ ansible_fqdn }}"
vault_port: 8200
vault_keysfile: "~/.hashicorp_vault_keys.json"
vault_admintokenfile: "~/.hashicorp_admin_token.json"
vault_sshkeysignertokenfile: "~/.hashicorp_sshkeysigner_token.json"
ssh_client: "ssh-client-signer"
sshrole_name: "sshrole"
default_user: "ansible"
def_lease_ttl: "10m"
max_lease_ttl: "20m"
ssh_host: "ssh-host-signer"
host_max_lease_ttl: "87600h"
hostrole_name: "hostrole"
allowed_domains: "localdomain,example.com"
