---

- name: Create GCP resources
  include_tasks:
    file: "gcp_create.yml"
  when: resource_action | default('create') == 'create'

- name: Destroy GCP resources
  include_tasks:
    file: "gcp_destroy.yml"
  when: resource_action | default('create') == 'destroy'
