---

- name: Target pool block
  block:

    - name: Destroy forwarding rules
      gcp_compute_forwarding_rule:
        name: "{{ service_name }}-{{ tp_item['name'] }}-forwarding-rule"
        region: "{{ project_region }}"
        project: "{{ gcp_data['project_name'] }}"
        auth_kind: "{{ gcp_data['cred_kind'] }}"
        service_account_file: "{{ gcp_data['cred_file'] }}"
        state: absent
      loop: "{{ project_data['services'][service_name]['target_pool_data'] |
          default([]) }}"
      loop_control:
        loop_var: tp_item
        label: "{{ service_name }}-{{ tp_item['name'] }}-forwarding-rule"

    - name: Destroy target pools
      gcp_compute_target_pool:
        name: "{{ service_name }}-{{ tp_item['name'] }}-target-pool"
        region: "{{ project_region }}"
        project: "{{ gcp_data['project_name'] }}"
        auth_kind: "{{ gcp_data['cred_kind'] }}"
        service_account_file: "{{ gcp_data['cred_file'] }}"
        state: absent
      loop: "{{ project_data['services'][service_name]['target_pool_data'] |
          default([]) }}"
      loop_control:
        loop_var: tp_item
        label: "{{ service_name }}-{{ tp_item['name'] }}-target-pool"

  when: project_data['services'][service_name]['target_pool_data'] is defined

- name: Destroy instances
  gcp_compute_instance:
    name: "{{ service_name }}-{{ instance_item['name'] }}-vm"
    zone: "{{ instance_item['zone'] }}"
    project: "{{ gcp_data['project_name'] }}"
    auth_kind: "{{ gcp_data['cred_kind'] }}"
    service_account_file: "{{ gcp_data['cred_file'] }}"
    scopes: "{{ project_data['services'][service_name]['scopes'] }}"
    state: absent
  loop: "{{ project_data['services'][service_name]['instances'] |
    default([]) }}"
  loop_control:
    loop_var: instance_item
    label: "{{ service_name }}-{{ instance_item['name'] }}-vm"

- name: Destroy external addresses
  gcp_compute_address:
    name: "{{ service_name }}-{{ address_item['name'] }}-address"
    region: "{{ project_region }}"
    project: "{{ gcp_data['project_name'] }}"
    auth_kind: "{{ gcp_data['cred_kind'] }}"
    service_account_file: "{{ gcp_data['cred_file'] }}"
    scopes: "{{ project_data['services'][service_name]['scopes'] }}"
    state: absent
  loop: "{{ project_data['services'][service_name]['ext_addresses'] |
    default([]) }}"
  loop_control:
    loop_var: address_item
    label: "{{ service_name }}-{{ address_item['name'] }}-address"

- name: Destroy external addresses per instance
  gcp_compute_address:
    name: "{{ service_name }}-{{ address_item['name'] }}-address"
    region: "{{ project_region }}"
    project: "{{ gcp_data['project_name'] }}"
    auth_kind: "{{ gcp_data['cred_kind'] }}"
    service_account_file: "{{ gcp_data['cred_file'] }}"
    scopes: "{{ project_data['services'][service_name]['scopes'] }}"
    state: absent
  loop: "{{ project_data['services'][service_name]['instances'] |
    default([]) }}"
  loop_control:
    loop_var: address_item
    label: "{{ service_name }}-{{ address_item['name'] }}-address"
  when: address_item['create_external_ip'] | default(False) | bool

- name: Destroy firewall rules
  gcp_compute_firewall:
    name: "{{ fw_item['name'] }}"
    project: "{{ gcp_data['project_name'] }}"
    auth_kind: "{{ gcp_data['cred_kind'] }}"
    service_account_file: "{{ gcp_data['cred_file'] }}"
    state: absent
  loop: "{{ project_data['services'][service_name]['fw_data'] |
    default([]) }}"
  loop_control:
    loop_var: fw_item
    label: "{{ fw_item['name'] }}"

- name: Destroy network
  gcp_compute_network:
    name: "{{ project_data['network']['name'] }}-network"
    project: "{{ gcp_data['project_name'] }}"
    auth_kind: "{{ gcp_data['cred_kind'] }}"
    service_account_file: "{{ gcp_data['cred_file'] }}"
    scopes: "{{ project_data['services'][service_name]['scopes'] }}"
    state: absent
  # In case any other services are still using this network
  ignore_errors: true
