---

- name: Cloud provider deployment
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - never
    - delete

  tasks:

    - name: Destroy cloud instance
      include_role:
        name: ansible-role-delete-instance

