---

- name: Cloud provider GitLab destruction
  hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - never
    - destroy

  tasks:

    - name: Destroy gitlab cloud instance
      include_role:
        name: ansible-role-gitlab-destroy

