---

- name: Install gitlab server on cloud instance
  hosts: gcp_ansible_group_gitlab
  become: yes
  gather_facts: yes
  tags:
    - gitlab

  vars_files:

    - ../vars/main.yml

  pre_tasks:

    - name: Clone external roles
      git:
        repo: "{{ repo_item['source'] }}"
        dest: "../roles/{{ repo_item['name'] }}"
        clone: yes
        version: "{{ repo_item['version'] | default(omit) }}"
      register: git_clone
      loop: "{{ external_roles }}"
      loop_control:
        loop_var: repo_item
      delegate_to: localhost
      run_once: yes
      become: no
      when: repo_item['name'] == 'ansible-role-gitlab'

  tasks:

    - name: Run gitlab server installation role
      include_role:
        name: ansible-role-gitlab

