---

- name: Install gitlab server on cloud instance
  hosts: gcp_ansible_group_gitlab
  become: yes
  gather_facts: yes
  tags:
    - gitlab

  roles:

    - name: Run gitlab server installation role
      role: geerlingguy.gitlab

