---

vault_addr: "{{ ansible_fqdn }}"
vault_port: 8200
vault_certs: "/etc/vault/certs"
vault_certfile: "{{ vault_certs }}/{{ansible_fqdn | regex_replace('^www\\.', '') }}.crt"
vault_user: "vault"
vault_group: "vault"
vault_service: "vault"
vault_keysfile: "~/.hashicorp_vault_keys.json"
